export const CHARACTER_DETAILS_LABELS = {
  backToCharacters: 'Back to Characters',
  status: 'Status:',
  gender: 'Gender:',
  species: 'Species:',
  type: 'Type:',
  origin: 'Origin:',
  currentLocation: 'Current Location:',
  episodes: 'Episodes',
  appearance: 'Appearance',
  loading: 'Loading character details...',
  failedToLoad: 'Failed to load character details: ',
  ofAllEpisodes: 'of all episodes',
  locationDetails: 'Location Details',
  locationName: 'Name:',
  locationType: 'Type:',
  locationDimension: 'Dimension:',
  locationResidents: 'Other Residents',
  moreResidents: 'more',
  locationLoading: 'Loading location details...',
  locationFailedToLoad: 'Failed to load location details',
};
